# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    paths:
      - 'first_tests_ci/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'first_tests_ci/**'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flask pytest
    - name: Lint with flake8
      run: |
        flake8 first_tests_ci/app.py first_tests_ci/test_app.py
    - name: Test with pytest
      run: |
        pytest first_tests_ci/test_app.py
    - name: Archive build artifacts
      run: |
        mkdir -p build
        cp first_tests_ci/app.py build/
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: flask-app
        path: build/
